### Cadastro de Usuário
POST http://localhost:3333/api/auth/register
Content-Type: application/json

{
  "nome": "Martin",
  "email": "martin@teste.com",
  "senha": "123"
}

###

### Fazer Login
POST http://localhost:3333/api/auth/login
Content-Type: application/json

{
  "email": "martin@teste.com",
  "senha": "123"
}